// <auto-generated />
using System;
using AzureMarketplaceSandbox.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AzureMarketplaceSandbox.Data.Migrations
{
    [DbContext(typeof(MarketplaceDbContext))]
    [Migration("20260408130024_ChangeIncludedQuantityToDecimal")]
    partial class ChangeIncludedQuantityToDecimal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("AzureMarketplaceSandbox.Domain.Models.AadInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("emailId");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("objectId");

                    b.Property<string>("Puid")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("puid");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("tenantId");

                    b.HasKey("Id");

                    b.ToTable("AadInfo");

                    b.HasAnnotation("Relational:JsonPropertyName", "purchaser");
                });

            modelBuilder.Entity("AzureMarketplaceSandbox.Domain.Models.MarketplaceToken", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Token");

                    b.ToTable("MarketplaceTokens");
                });

            modelBuilder.Entity("AzureMarketplaceSandbox.Domain.Models.MeteringDimension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DimensionId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("displayName");

                    b.Property<string>("OfferId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerUnit")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("pricePerUnit");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("unitOfMeasure");

                    b.HasKey("Id");

                    b.HasIndex("OfferId");

                    b.ToTable("MeteringDimensions");
                });

            modelBuilder.Entity("AzureMarketplaceSandbox.Domain.Models.Offer", b =>
                {
                    b.Property<string>("OfferId")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("offerId");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("currency");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("displayName");

                    b.Property<string>("PublisherId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("publisherId");

                    b.HasKey("OfferId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("AzureMarketplaceSandbox.Domain.Models.Operation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("action");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("activityId");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("errorMessage");

                    b.Property<string>("ErrorStatusCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("errorStatusCode");

                    b.Property<string>("OfferId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("offerId");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("planId");

                    b.Property<string>("PublisherId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("publisherId");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("quantity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("status");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("subscriptionId");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("timeStamp");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("AzureMarketplaceSandbox.Domain.Models.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BillingTermUnit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("displayName");

                    b.Property<bool>("HasFreeTrials")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("hasFreeTrials");

                    b.Property<bool>("IsPricePerSeat")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("isPricePerSeat");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("isPrivate");

                    b.Property<bool>("IsStopSell")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("isStopSell");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("market");

                    b.Property<int>("MaxQuantity")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("maxQuantity");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("minQuantity");

                    b.Property<string>("OfferId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("planId");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubscriptionTermUnit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TermDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OfferId");

                    b.ToTable("Plans");

                    b.HasAnnotation("Relational:JsonPropertyName", "plans");
                });

            modelBuilder.Entity("AzureMarketplaceSandbox.Domain.Models.PlanMeteringDimension", b =>
                {
                    b.Property<int>("PlanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeteringDimensionId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("IncludedQuantity")
                        .HasColumnType("TEXT");

                    b.HasKey("PlanId", "MeteringDimensionId");

                    b.HasIndex("MeteringDimensionId");

                    b.ToTable("PlanMeteringDimensions");
                });

            modelBuilder.Entity("AzureMarketplaceSandbox.Domain.Models.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("id");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("autoRenew");

                    b.Property<int>("BeneficiaryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("created");

                    b.Property<bool>("IsFreeTrial")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("isFreeTrial");

                    b.Property<bool>("IsTest")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("isTest");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("name");

                    b.Property<string>("OfferId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("offerId");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("planId");

                    b.Property<string>("PublisherId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("publisherId");

                    b.Property<int>("PurchaserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("quantity");

                    b.Property<string>("SaasSubscriptionStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("saasSubscriptionStatus");

                    b.Property<string>("SandboxType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("sandboxType");

                    b.Property<string>("SessionMode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("sessionMode");

                    b.Property<int>("TermId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiaryId");

                    b.HasIndex("PurchaserId");

                    b.HasIndex("TermId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("AzureMarketplaceSandbox.Domain.Models.SubscriptionTerm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("endDate");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("startDate");

                    b.Property<string>("TermUnit")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("termUnit");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionTerm");

                    b.HasAnnotation("Relational:JsonPropertyName", "term");
                });

            modelBuilder.Entity("AzureMarketplaceSandbox.Domain.Models.UsageEvent", b =>
                {
                    b.Property<Guid>("UsageEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("usageEventId");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("dimension");

                    b.Property<DateTime>("EffectiveStartTime")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("effectiveStartTime");

                    b.Property<DateTime>("MessageTime")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("messageTime");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("planId");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL")
                        .HasJsonPropertyName("quantity");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("resourceId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("status");

                    b.HasKey("UsageEventId");

                    b.ToTable("UsageEvents");
                });

            modelBuilder.Entity("AzureMarketplaceSandbox.Domain.Models.WebhookDeliveryLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WebhookDeliveryLogs");
                });

            modelBuilder.Entity("AzureMarketplaceSandbox.Domain.Models.MeteringDimension", b =>
                {
                    b.HasOne("AzureMarketplaceSandbox.Domain.Models.Offer", "Offer")
                        .WithMany("MeteringDimensions")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("AzureMarketplaceSandbox.Domain.Models.Operation", b =>
                {
                    b.HasOne("AzureMarketplaceSandbox.Domain.Models.Subscription", "Subscription")
                        .WithMany("Operations")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("AzureMarketplaceSandbox.Domain.Models.Plan", b =>
                {
                    b.HasOne("AzureMarketplaceSandbox.Domain.Models.Offer", "Offer")
                        .WithMany("Plans")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("AzureMarketplaceSandbox.Domain.Models.PlanMeteringDimension", b =>
                {
                    b.HasOne("AzureMarketplaceSandbox.Domain.Models.MeteringDimension", "MeteringDimension")
                        .WithMany("PlanMeteringDimensions")
                        .HasForeignKey("MeteringDimensionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AzureMarketplaceSandbox.Domain.Models.Plan", "Plan")
                        .WithMany("PlanMeteringDimensions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeteringDimension");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("AzureMarketplaceSandbox.Domain.Models.Subscription", b =>
                {
                    b.HasOne("AzureMarketplaceSandbox.Domain.Models.AadInfo", "Beneficiary")
                        .WithMany()
                        .HasForeignKey("BeneficiaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AzureMarketplaceSandbox.Domain.Models.AadInfo", "Purchaser")
                        .WithMany()
                        .HasForeignKey("PurchaserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AzureMarketplaceSandbox.Domain.Models.SubscriptionTerm", "Term")
                        .WithMany()
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beneficiary");

                    b.Navigation("Purchaser");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("AzureMarketplaceSandbox.Domain.Models.MeteringDimension", b =>
                {
                    b.Navigation("PlanMeteringDimensions");
                });

            modelBuilder.Entity("AzureMarketplaceSandbox.Domain.Models.Offer", b =>
                {
                    b.Navigation("MeteringDimensions");

                    b.Navigation("Plans");
                });

            modelBuilder.Entity("AzureMarketplaceSandbox.Domain.Models.Plan", b =>
                {
                    b.Navigation("PlanMeteringDimensions");
                });

            modelBuilder.Entity("AzureMarketplaceSandbox.Domain.Models.Subscription", b =>
                {
                    b.Navigation("Operations");
                });
#pragma warning restore 612, 618
        }
    }
}
