// <auto-generated />
using System;
using AzureMarketplaceSandbox.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AzureMarketplaceSandbox.Data.Migrations
{
    [DbContext(typeof(MarketplaceDbContext))]
    partial class MarketplaceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AzureMarketplaceSandbox.Domain.Models.AadInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("emailId");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("objectId");

                    b.Property<string>("Puid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("puid");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("tenantId");

                    b.HasKey("Id");

                    b.ToTable("AadInfo");

                    b.HasAnnotation("Relational:JsonPropertyName", "purchaser");
                });

            modelBuilder.Entity("AzureMarketplaceSandbox.Domain.Models.MarketplaceToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("MarketplaceTokens");
                });

            modelBuilder.Entity("AzureMarketplaceSandbox.Domain.Models.MeteringDimension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DimensionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("displayName");

                    b.Property<int>("OfferId")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerUnit")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasJsonPropertyName("pricePerUnit");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("unitOfMeasure");

                    b.HasKey("Id");

                    b.HasIndex("OfferId");

                    b.ToTable("MeteringDimensions");
                });

            modelBuilder.Entity("AzureMarketplaceSandbox.Domain.Models.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("currency");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("displayName");

                    b.Property<string>("OfferId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasJsonPropertyName("offerId");

                    b.Property<string>("PublisherId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("publisherId");

                    b.HasKey("Id");

                    b.HasIndex("OfferId")
                        .IsUnique();

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("AzureMarketplaceSandbox.Domain.Models.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("action");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("activityId");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("errorMessage");

                    b.Property<string>("ErrorStatusCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("errorStatusCode");

                    b.Property<string>("OfferId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("offerId");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("id");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("planId");

                    b.Property<string>("PublisherId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("publisherId");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasJsonPropertyName("quantity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("status");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("subscriptionId");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2")
                        .HasJsonPropertyName("timeStamp");

                    b.HasKey("Id");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("AzureMarketplaceSandbox.Domain.Models.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingTermUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("displayName");

                    b.Property<bool>("HasFreeTrials")
                        .HasColumnType("bit")
                        .HasJsonPropertyName("hasFreeTrials");

                    b.Property<bool>("IsPricePerSeat")
                        .HasColumnType("bit")
                        .HasJsonPropertyName("isPricePerSeat");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit")
                        .HasJsonPropertyName("isPrivate");

                    b.Property<bool>("IsStopSell")
                        .HasColumnType("bit")
                        .HasJsonPropertyName("isStopSell");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("market");

                    b.Property<int>("MaxQuantity")
                        .HasColumnType("int")
                        .HasJsonPropertyName("maxQuantity");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("int")
                        .HasJsonPropertyName("minQuantity");

                    b.Property<int>("OfferId")
                        .HasColumnType("int");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("planId");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SubscriptionTermUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TermDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OfferId");

                    b.ToTable("Plans");

                    b.HasAnnotation("Relational:JsonPropertyName", "plans");
                });

            modelBuilder.Entity("AzureMarketplaceSandbox.Domain.Models.PlanMeteringDimension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("IncludedQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("MeteringDimensionId")
                        .HasColumnType("int");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MeteringDimensionId");

                    b.HasIndex("PlanId");

                    b.ToTable("PlanMeteringDimensions");
                });

            modelBuilder.Entity("AzureMarketplaceSandbox.Domain.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("bit")
                        .HasJsonPropertyName("autoRenew");

                    b.Property<int>("BeneficiaryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2")
                        .HasJsonPropertyName("created");

                    b.Property<bool>("IsFreeTrial")
                        .HasColumnType("bit")
                        .HasJsonPropertyName("isFreeTrial");

                    b.Property<bool>("IsTest")
                        .HasColumnType("bit")
                        .HasJsonPropertyName("isTest");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("name");

                    b.Property<string>("OfferId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("offerId");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("planId");

                    b.Property<string>("PublisherId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("publisherId");

                    b.Property<int>("PurchaserId")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasJsonPropertyName("quantity");

                    b.Property<string>("SaasSubscriptionStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("saasSubscriptionStatus");

                    b.Property<string>("SandboxType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("sandboxType");

                    b.Property<string>("SessionMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("sessionMode");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("id");

                    b.Property<int>("TermId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiaryId");

                    b.HasIndex("PurchaserId");

                    b.HasIndex("TermId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("AzureMarketplaceSandbox.Domain.Models.SubscriptionTerm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2")
                        .HasJsonPropertyName("endDate");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2")
                        .HasJsonPropertyName("startDate");

                    b.Property<string>("TermUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("termUnit");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionTerm");

                    b.HasAnnotation("Relational:JsonPropertyName", "term");
                });

            modelBuilder.Entity("AzureMarketplaceSandbox.Domain.Models.UsageEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("dimension");

                    b.Property<DateTime>("EffectiveStartTime")
                        .HasColumnType("datetime2")
                        .HasJsonPropertyName("effectiveStartTime");

                    b.Property<DateTime>("MessageTime")
                        .HasColumnType("datetime2")
                        .HasJsonPropertyName("messageTime");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("planId");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasJsonPropertyName("quantity");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("resourceId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("status");

                    b.Property<Guid>("UsageEventId")
                        .HasColumnType("uniqueidentifier")
                        .HasJsonPropertyName("usageEventId");

                    b.HasKey("Id");

                    b.ToTable("UsageEvents");
                });

            modelBuilder.Entity("AzureMarketplaceSandbox.Domain.Models.WebhookDeliveryLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("int");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WebhookDeliveryLogId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("WebhookDeliveryLogs");
                });

            modelBuilder.Entity("AzureMarketplaceSandbox.Domain.Models.MeteringDimension", b =>
                {
                    b.HasOne("AzureMarketplaceSandbox.Domain.Models.Offer", "Offer")
                        .WithMany("MeteringDimensions")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("AzureMarketplaceSandbox.Domain.Models.Plan", b =>
                {
                    b.HasOne("AzureMarketplaceSandbox.Domain.Models.Offer", "Offer")
                        .WithMany("Plans")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("AzureMarketplaceSandbox.Domain.Models.PlanMeteringDimension", b =>
                {
                    b.HasOne("AzureMarketplaceSandbox.Domain.Models.MeteringDimension", "MeteringDimension")
                        .WithMany("PlanMeteringDimensions")
                        .HasForeignKey("MeteringDimensionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AzureMarketplaceSandbox.Domain.Models.Plan", "Plan")
                        .WithMany("PlanMeteringDimensions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MeteringDimension");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("AzureMarketplaceSandbox.Domain.Models.Subscription", b =>
                {
                    b.HasOne("AzureMarketplaceSandbox.Domain.Models.AadInfo", "Beneficiary")
                        .WithMany()
                        .HasForeignKey("BeneficiaryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AzureMarketplaceSandbox.Domain.Models.AadInfo", "Purchaser")
                        .WithMany()
                        .HasForeignKey("PurchaserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AzureMarketplaceSandbox.Domain.Models.SubscriptionTerm", "Term")
                        .WithMany()
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beneficiary");

                    b.Navigation("Purchaser");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("AzureMarketplaceSandbox.Domain.Models.MeteringDimension", b =>
                {
                    b.Navigation("PlanMeteringDimensions");
                });

            modelBuilder.Entity("AzureMarketplaceSandbox.Domain.Models.Offer", b =>
                {
                    b.Navigation("MeteringDimensions");

                    b.Navigation("Plans");
                });

            modelBuilder.Entity("AzureMarketplaceSandbox.Domain.Models.Plan", b =>
                {
                    b.Navigation("PlanMeteringDimensions");
                });
#pragma warning restore 612, 618
        }
    }
}
